version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    working_directory: /go/src/github.com/WoTTsecurity/ghostunnel
    steps:
      - checkout
      - run:
          name: Install depenedencies
          command: |
               sudo dpkg --add-architecture armel
               sudo apt-get update
               sudo apt-get install libltdl-dev devscripts crossbuild-essential-armel libltdl-dev:armel
      - run:
          name: Build x86
          command: |
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=amd64 -aamd64 -i -us -uc -b
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=arm -aarmel -i -us -uc -b
      - run:
          name: Store artifacts
          command: |
              mkdir -p /tmp/deb
              mv ../*.deb /tmp/deb
      - store_artifacts:
          path: /tmp/deb
