# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/WoTTsecurity/ghostunnel
    steps:
      - checkout
      - run:
          name: Install depenedencies
          command: |
              #  sudo dpkg --add-architecture armel
              #  sudo apt-get update
               sudo apt-get install libltdl-dev devscripts 
               #crossbuild-essential-armel libltdl-dev:armel
      - run:
          name: Build x86
          command: |
              #  go get -v github.com/WoTTsecurity/ghostunnel
              #  go build -v -x
               # GOARM=6 GOOS=linux GOARCH=arm go build -v -x
              #  debuild -i -us -uc -b
              debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=amd64 -aamd64 -i -us -uc -b
              # debuild  --prepend-path=/usr/local/go/bin --set-envvar GOARCH=arm -aarmel -i -us -uc -b
      - run:
          name: Store artifacts
          command: |
              mkdir -p /tmp/deb
              mv ../*.deb /tmp/deb
      - store_artifacts:
          path: /tmp/deb
